apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-deployment
  namespace: axion-app
spec:
  selector:
    matchLabels:
      app: simulator-deployment
  template:
    metadata:
      labels:
        app: simulator-deployment
    spec:
      containers:
      - name: simulator-deployment
        image: axionacrdevnmkdck.azurecr.io/axion-simulator:IMAGE_TAG
        imagePullPolicy: IfNotPresent

        env:
          - name: API_URL
            value: "http://ingestion-service.axion-app.svc.cluster.local:80/api/v1/telemetry/ingest"

          - name: INTERVAL_SECONDS
            value: "5"
        