apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-deployment
  namespace: axion-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ingestion-deployment

  template:
    metadata:
      labels:
        app: ingestion-deployment

    spec:
      containers:
        - name: ingestion-deployment
          image: axionacrdevnmkdck.azurecr.io/axion-ingestion:IMAGE_TAG
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL